export const GOOGLE = 'Google Sheets' as const
export const GOOGLE_URL = 'docs.google.com' as const
export const EXCEL = 'Excel Online' as const
export const EXCEL_URL = 'onedrive.live.com' as const
export const NOTION = 'Notion' as const
export const NOTION_URL = 'notion.so' as const
export const FETCH_ERROR_MESSAGE = 'An error occurred while getting the formula' as const
export const DEFAULT_ERROR_MESSAGE = 'Formula could not be created' as const
export const ONE_HUNDRED = 100 as const
export const ONE_THOUSAND = 1000 as const
